/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import helper.ShareData;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Thuan
 */
public class MainFrame extends javax.swing.JFrame {
    private QLThongTinSVPanel mStudentPanel ;
    private QLDiemPanel gpaPanel ;
    private QLMonHocPanel monHocPanel ;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
        
        //setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
        
        LoginDialogForm loginFrame = new LoginDialogForm(this,true);
        loginFrame.setVisible(true);
        processLoginSuccessful(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tplMainBoard = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblLoginName = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        tbrLogOut = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        tbrQLSV = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        tbrQLDiem = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        tbrQLMonHoc = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trang chủ");

        lblLoginName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblRole.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Xin Chào !");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLoginName, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLoginName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblRole, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jToolBar1.setBorder(null);
        jToolBar1.setRollover(true);

        tbrLogOut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tbrLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout-icon-16.png"))); // NOI18N
        tbrLogOut.setText("Đăng xuất");
        tbrLogOut.setMinimumSize(new java.awt.Dimension(81, 43));
        tbrLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrLogOutActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrLogOut);
        jToolBar1.add(jSeparator4);

        tbrQLSV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tbrQLSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/10207-man-student-light-skin-tone-icon-16.png"))); // NOI18N
        tbrQLSV.setText("Quản lý Sinh Viên");
        tbrQLSV.setMinimumSize(new java.awt.Dimension(119, 43));
        tbrQLSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrQLSVActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrQLSV);
        jToolBar1.add(jSeparator6);

        tbrQLDiem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tbrQLDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/gpa-icon.png"))); // NOI18N
        tbrQLDiem.setText("Quản lý điểm");
        tbrQLDiem.setMinimumSize(new java.awt.Dimension(97, 43));
        tbrQLDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrQLDiemActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrQLDiem);
        jToolBar1.add(jSeparator1);

        tbrQLMonHoc.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        tbrQLMonHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Actions-document-edit-icon-16.png"))); // NOI18N
        tbrQLMonHoc.setText("Quản lý môn học");
        tbrQLMonHoc.setPreferredSize(new java.awt.Dimension(120, 43));
        tbrQLMonHoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrQLMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrQLMonHocActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrQLMonHoc);

        jSeparator2.setBackground(new java.awt.Color(255, 153, 0));
        jSeparator2.setForeground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addComponent(tplMainBoard, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 119, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(tplMainBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbrLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrLogOutActionPerformed
        LoginDialogForm loginFrame = new LoginDialogForm(this, true);
        this.setVisible(false);
        loginFrame.setVisible(true);
        this.setVisible(true);
        processLoginSuccessful();
    }//GEN-LAST:event_tbrLogOutActionPerformed

    private void tbrQLSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrQLSVActionPerformed
       if(mStudentPanel == null){
           try {
               try {
                   mStudentPanel = new QLThongTinSVPanel();
               } catch (IOException ex) {
                   Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
               }
           } catch (SQLException ex) {
               Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
           }
            ImageIcon icon = new ImageIcon(getClass().getResource("/icons/10207-man-student-light-skin-tone-icon-16.png"));
            tplMainBoard.addTab("Quản lý Sinh Viên", icon, mStudentPanel, "Quản lý Sinh Viên");    
        }
       tplMainBoard.setSelectedComponent(mStudentPanel);    }//GEN-LAST:event_tbrQLSVActionPerformed

    private void tbrQLDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrQLDiemActionPerformed
        if(gpaPanel == null){
            try {
                try {
                    gpaPanel = new QLDiemPanel();
                } catch (IOException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            ImageIcon icon = new ImageIcon(getClass().getResource("/icons/gpa-icon.png"));
            tplMainBoard.addTab("Quản lý điểm", icon, gpaPanel, "Quản lý điểm");    
        }
       tplMainBoard.setSelectedComponent(gpaPanel);
    }//GEN-LAST:event_tbrQLDiemActionPerformed

    private void tbrQLMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrQLMonHocActionPerformed
        if(monHocPanel == null){
            try {
                monHocPanel = new QLMonHocPanel();
            } catch (Exception e) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, e);
            }
            ImageIcon icon = new ImageIcon(getClass().getResource("/icons/Actions-document-edit-icon-16.png"));
            tplMainBoard.addTab("Quản lý môn học",icon, monHocPanel,"Quản lý môn học");
        }
        tplMainBoard.setSelectedComponent(monHocPanel);
    }//GEN-LAST:event_tbrQLMonHocActionPerformed
    private void processLoginSuccessful(){
        lblLoginName.setText(ShareData.userLogin.getUsername());
        lblRole.setText(ShareData.userLogin.getRole());
        tplMainBoard.removeAll();
        gpaPanel = null;
        mStudentPanel = null;
        monHocPanel = null;
        
        if(lblRole.getText().equals("Sinh Viên")){
            tbrQLMonHoc.setVisible(false);
            tbrQLDiem.setVisible(true);
            tbrQLSV.setVisible(true);
            
            
        }
        else if(lblRole.getText().equals("Giáo Viên")){
            tbrQLMonHoc.setVisible(false);
            tbrQLDiem.setVisible(true);
            tbrQLSV.setVisible(true);
            
        }else if(lblRole.getText().equals("Admin")){
            tbrQLSV.setVisible(false);
            tbrQLDiem.setVisible(false);
            tbrQLMonHoc.setVisible(true);
            jSeparator1.setVisible(false);
            jSeparator6.setVisible(false);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblLoginName;
    private javax.swing.JLabel lblRole;
    private javax.swing.JButton tbrLogOut;
    private javax.swing.JButton tbrQLDiem;
    private javax.swing.JButton tbrQLMonHoc;
    private javax.swing.JButton tbrQLSV;
    private javax.swing.JTabbedPane tplMainBoard;
    // End of variables declaration//GEN-END:variables
}
