/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.KQMonHocDao;
import dao.MonHocDao;
import dao.SinhVienDao;
import helper.DataValidator;
import helper.MessageDialogHelper;
import helper.ShareData;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import model.KQMonHoc;
import model.MonHoc;
import model.SinhVien;
import model.User;

/**
 *
 * @author Thuan
 */
public class QLDiemPanel extends javax.swing.JPanel {

    private MainFrame parentFrame;
    private DefaultTableModel defaultTableModel;
    private String bangDiem = new String();
    /**
     * Creates new form QLDiemPanel
     */
    public QLDiemPanel() throws SQLException, IOException {
        initComponents();
        initTable();
        loadDataToTable();
        if(ShareData.userLogin.getRole().equals("Sinh Viên"))
             roleSV(ShareData.userLogin);
    }

    private void initTable() {
        defaultTableModel = new DefaultTableModel();
        defaultTableModel.setColumnIdentifiers(new String[]{"Mã môn", "Tên môn", "Số tín chỉ", "Điểm số", "Điểm chữ"});
        tblGPA.setModel(defaultTableModel);
    }

    private void loadDataToTable() throws SQLException {
        try {
            KQMonHocDao kqMonHocDao = new KQMonHocDao();
            MonHocDao monHocDao = new MonHocDao();
            
            defaultTableModel.setRowCount(0);

            try{
                List<KQMonHoc> list = kqMonHocDao.findAllKQMonHoc(txtMaSinhVienSearch.getText(), cbxNamHoc.getSelectedItem().toString(), Integer.parseInt(cbxHocKy.getSelectedItem().toString()));            
                float GPA = 0, soTinChi = 0;
                
                for(KQMonHoc kqMonHoc : list){
                    MonHoc monHoc = monHocDao.findByMaMon(kqMonHoc.getMaMon());
                    defaultTableModel.addRow(new Object[]{
                    monHoc.getMaMon(), monHoc.getTenMon(), monHoc.getSoTinChi(), kqMonHoc.getDiemSo(), kqMonHoc.getDiemChu()
                    });
                    GPA+= kqMonHoc.getDiemSo()*monHoc.getSoTinChi();
                    soTinChi+=monHoc.getSoTinChi();
                }
                GPA = GPA/soTinChi;
                if(GPA < 9 && GPA >= 8)
                    lblXepLoai.setText("GIỎI");
                else if(GPA < 8&& GPA >= 6.5)
                    lblXepLoai.setText("KHÁ");
                else if(GPA < 6.5&& GPA >= 5)
                    lblXepLoai.setText("TRUNG BÌNH");
                else if(GPA < 5 && GPA >= 4)
                    lblXepLoai.setText("YẾU");
                else if(GPA < 4)
                    lblXepLoai.setText("KÉM");
                else if(GPA >= 9)
                    lblXepLoai.setText("XUẤT SẮC");
                else
                    lblXepLoai.setText("NULL");
                lblGPA.setText( String.format("%.2f",GPA));
            }catch(Exception e){
                e.printStackTrace();
            }

            defaultTableModel.fireTableDataChanged();
        }
        
        catch(Exception e){
            e.printStackTrace();
            MessageDialogHelper.showMessageDialog(parentFrame, e.getMessage(), "Error");
        }
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblGPA = new javax.swing.JLabel();
        lblXepLoai = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbxNamHoc = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbxHocKy = new javax.swing.JComboBox<>();
        lblNhapDiem = new javax.swing.JLabel();
        lblMaMon = new javax.swing.JLabel();
        txtMaMon = new javax.swing.JTextField();
        lblDiemSo = new javax.swing.JLabel();
        txtDiem = new javax.swing.JTextField();
        lblTenMon1 = new javax.swing.JLabel();
        lblTenMon = new javax.swing.JLabel();
        lblSoTinChi1 = new javax.swing.JLabel();
        lblTinChi = new javax.swing.JLabel();
        lblDiemChu1 = new javax.swing.JLabel();
        lblDiemChu = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaSinhVienSearch = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        txtHoTen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGPA = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnXuatBangDiem = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();

        jLabel7.setText("jLabel7");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Điểm trung bình học kỳ");

        lblGPA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGPA.setForeground(new java.awt.Color(255, 0, 0));
        lblGPA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGPA.setText("10.0");

        lblXepLoai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblXepLoai.setForeground(new java.awt.Color(255, 0, 0));
        lblXepLoai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Xếp loại");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGPA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblXepLoai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(90, 90, 90))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblGPA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(5, 5, 5)
                .addComponent(lblXepLoai, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );

        jLabel5.setText("Năm học :");

        cbxNamHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020 - 2021", "2021 - 2022", "2022 - 2023" }));

        jLabel6.setText("Học kỳ");

        cbxHocKy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        lblNhapDiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNhapDiem.setText("Nhập Điểm");

        lblMaMon.setText("Mã môn");

        txtMaMon.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtMaMonMouseMoved(evt);
            }
        });
        txtMaMon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaMonFocusLost(evt);
            }
        });
        txtMaMon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtMaMonMouseReleased(evt);
            }
        });
        txtMaMon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMaMonKeyPressed(evt);
            }
        });

        lblDiemSo.setText("Điểm số ");

        txtDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDiemMouseClicked(evt);
            }
        });
        txtDiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDiemKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiemKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiemKeyTyped(evt);
            }
        });

        lblTenMon1.setText("Tên môn");

        lblTenMon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblSoTinChi1.setText("Số tín chỉ");

        lblTinChi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblDiemChu1.setText("Điểm chữ");

        lblDiemChu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jSeparator2.setForeground(new java.awt.Color(255, 153, 0));

        jSeparator4.setForeground(new java.awt.Color(255, 153, 0));

        jSeparator5.setForeground(new java.awt.Color(255, 153, 0));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblNhapDiem))
                        .addGap(29, 29, 29)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxHocKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                            .addComponent(lblTenMon1)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblTenMon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                            .addComponent(lblMaMon)
                                            .addGap(21, 21, 21)
                                            .addComponent(txtMaMon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(lblDiemSo)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(lblSoTinChi1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblTinChi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(lblDiemChu1)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblDiemChu, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(21, 21, 21)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addComponent(jSeparator4)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxHocKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(lblNhapDiem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblMaMon)
                                            .addComponent(txtMaMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblTenMon, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblTenMon1)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblSoTinChi1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                                        .addComponent(lblTinChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDiemSo)
                                    .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDiemChu1)
                                    .addComponent(lblDiemChu, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator5)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 41, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ ĐIỂM");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator1.setForeground(new java.awt.Color(255, 153, 0));

        jLabel2.setText("Mã sinh viên");

        btnFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search-icon-16.png"))); // NOI18N
        btnFind.setText("Tìm kiếm");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        txtHoTen.setEditable(false);
        txtHoTen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtHoTen.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtHoTen.setSelectionColor(new java.awt.Color(204, 204, 204));

        jLabel4.setText("Họ và tên");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jSeparator3.setForeground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaSinhVienSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(txtHoTen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFind))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator3)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaSinhVienSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tblGPA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblGPA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGPAMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGPA);

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Actions-edit-delete-icon-16.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new-icon-16.png"))); // NOI18N
        btnNew.setText("Làm mới");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Save-icon.png"))); // NOI18N
        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnXuatBangDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Actions-document-edit-icon-16.png"))); // NOI18N
        btnXuatBangDiem.setText("Xuất bảng điểm");
        btnXuatBangDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatBangDiemActionPerformed(evt);
            }
        });

        jSeparator6.setForeground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnSave)
                        .addGap(18, 18, 18)
                        .addComponent(btnNew)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXuatBangDiem))
                    .addComponent(jSeparator6))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnDelete)
                    .addComponent(btnNew)
                    .addComponent(btnXuatBangDiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        try {
            SinhVienDao svDao = new SinhVienDao();
            SinhVien sv = svDao.findByID(txtMaSinhVienSearch.getText());
            if(sv == null){
                MessageDialogHelper.showMessageDialog(parentFrame, "Không tìm thấy sinh viên", "Lỗi");
                return;
            }
            else{
                
                txtHoTen.setText(sv.getHoTen());
                loadDataToTable();
             }

        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentFrame, e.getMessage() , "Error");
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        txtMaSinhVienSearch.setText("");
        txtHoTen.setText("");
        txtDiem.setText("");
        txtMaMon.setText("");
        lblDiemChu.setText("");
        lblGPA.setText("");
        lblTenMon.setText("");
        lblTinChi.setText("");
        
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtMaMon, sb, "Phải nhập mã môn học !!! ");
        DataValidator.validateEmpty(txtDiem, sb, "Phải nhập điểm số !!! ");
        DataValidator.validateScore(txtDiem, sb, "Điểm nhập sai định dạng !!");

        if(sb.length() > 0){
            MessageDialogHelper.showErrorDialog(parentFrame,sb.toString(), "Error");
            return;
        }
        try {
            KQMonHoc result = new KQMonHoc();
            result.setMaMon(txtMaMon.getText());
            result.setMaSinhVien(txtMaSinhVienSearch.getText());
            result.setDiemSo(Float.parseFloat(txtDiem.getText()));
            result.setDiemChu(xepLoai(Float.parseFloat(txtDiem.getText())));
            result.setNamHoc(cbxNamHoc.getSelectedItem().toString());
            result.setHocKy(Integer.parseInt(cbxHocKy.getSelectedItem().toString()));

            KQMonHocDao resultDao = new KQMonHocDao();
            KQMonHoc kqmh = resultDao.find(result.getMaSinhVien(), result.getMaMon(), result.getNamHoc(), result.getHocKy());
            if( kqmh == null){
                if(resultDao.insert(result))
                    MessageDialogHelper.showMessageDialog(parentFrame, "Điểm đã được thêm", "Thành công");
                else    
                    MessageDialogHelper.showMessageDialog(parentFrame, "Điểm chưa được thêm", "Lỗi");            
            }
            else{
                if(resultDao.update(result, kqmh.getMaKQ()))
                    MessageDialogHelper.showMessageDialog(parentFrame, "Điểm đã được cập nhật", "Thành công");
                else    
                    MessageDialogHelper.showMessageDialog(parentFrame, "Điểm chưa được cập nhật", "Lỗi");
            }

            loadDataToTable();
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showMessageDialog(parentFrame, e.getMessage(), "Error");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            if(txtMaSinhVienSearch.getText().equals("")){
                MessageDialogHelper.showErrorDialog(parentFrame, "Mã sinh viên không được trống", "Lỗi");
            }else{
                KQMonHocDao resultDao = new KQMonHocDao();
                KQMonHoc result = resultDao.find(txtMaSinhVienSearch.getText(), txtMaMon.getText(),cbxNamHoc.getSelectedItem().toString(), Integer.parseInt(cbxHocKy.getSelectedItem().toString()) );
                if(result == null){
                    MessageDialogHelper.showMessageDialog(parentFrame, "Không tìm thấy kết quả cần xóa", "Error");
                    return;
                }
                if(MessageDialogHelper.showConfirmDialog(parentFrame, "Bạn chắc chắn muốn xóa", "Xác nhận") == JOptionPane.NO_OPTION)
                return;
                if(resultDao.delete(result))
                    MessageDialogHelper.showMessageDialog(parentFrame, "Xóa thành công", "Thành công");
                else
                    MessageDialogHelper.showMessageDialog(parentFrame, "Không xóa được", "Thất bại");
            }
            loadDataToTable();
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showMessageDialog(parentFrame, e.getMessage(), "Error");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtMaMonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaMonKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            xacDinhMonHoc();      
        }
    }//GEN-LAST:event_txtMaMonKeyPressed

    private void txtMaMonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMaMonMouseReleased
        xacDinhMonHoc();            
    }//GEN-LAST:event_txtMaMonMouseReleased


    private void txtMaMonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMaMonMouseMoved
        xacDinhMonHoc();   
    }//GEN-LAST:event_txtMaMonMouseMoved

    private void txtMaMonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaMonFocusLost
        xacDinhMonHoc();
    }//GEN-LAST:event_txtMaMonFocusLost

    private void tblGPAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGPAMouseClicked
        try {
            int row = tblGPA.getSelectedRow();
            if(row >= 0 ){
                
                String maSinhVien =  txtMaSinhVienSearch.getText(); 
                String maMon = (String) tblGPA.getValueAt(row, 0);
                float diem =  Float.parseFloat(tblGPA.getValueAt(row, 3).toString());
                String namHoc =  cbxNamHoc.getSelectedItem().toString();
                int hocKy = Integer.parseInt(cbxHocKy.getSelectedItem().toString());
                
                KQMonHocDao kqMonHocDao =  new KQMonHocDao();
                KQMonHoc kqMocHoc = kqMonHocDao.find(maSinhVien, maMon, namHoc, hocKy);
                SinhVienDao svDao = new SinhVienDao();
                SinhVien sv = svDao.findByID(maSinhVien);

                if(kqMocHoc != null){
                    
                    txtHoTen.setText(sv.getHoTen());
                    txtMaMon.setText(maMon);
                    xacDinhMonHoc();
                    txtDiem.setText(String.valueOf(diem));
                    lblDiemChu.setText(xepLoai(diem));
                                        
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentFrame, e.getMessage(), "Error");

        }
    }//GEN-LAST:event_tblGPAMouseClicked

    private void txtDiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDiemMouseClicked
        xacDinhMonHoc();
    }//GEN-LAST:event_txtDiemMouseClicked

    private void txtDiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiemKeyPressed
        if(!txtDiem.getText().equals(""))
            lblDiemChu.setText(xepLoai(Float.parseFloat(txtDiem.getText()) ));      
                
    }//GEN-LAST:event_txtDiemKeyPressed

    private void btnXuatBangDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatBangDiemActionPerformed
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter txtFilter = new FileNameExtensionFilter("txt", "txt");
        fc.setFileFilter(txtFilter);
        
        fc.showSaveDialog(this);
        File f = fc.getSelectedFile();
        
        bangDiem+="\tTRƯỜNG ĐẠI HỌC CẦN THƠ\n" + "Mã số sinh viên: " + txtMaSinhVienSearch.getText() + " - Họ và tên: " + txtHoTen.getText() + "\n";
        bangDiem+="Năm học: " + cbxNamHoc.getSelectedItem().toString() + " | Học kỳ: " + Integer.parseInt(cbxHocKy.getSelectedItem().toString()) + "\n\n";
        bangDiem +="Mã môn\t\t Tên môn\t           Số tín chỉ\t       Điểm số\t  Điểm chữ\n";
        for(int i = 1; i <= 85; i++){
            bangDiem+="-";
        }
        bangDiem+="\n";
            
        try {
            FileWriter fw = new FileWriter(f,StandardCharsets.UTF_8);
            int n = tblGPA.getRowCount();
            int m = tblGPA.getColumnCount();
            for(int i = 0; i < n ; i++){
                for(int j = 0; j < m; j++){
                    bangDiem+= tblGPA.getValueAt(i, j) +"\t";
                    if(tblGPA.getValueAt(i, j).toString().length() < 15)
                        bangDiem+="\t";
                    if(j==1)
                        if(tblGPA.getValueAt(i, 1).toString().length() < 25)
                            bangDiem+="\t";
                }
                bangDiem+="\n";
            }
            for(int i = 1; i <= 85; i++){
                bangDiem+="-";
             }
            bangDiem+="\n";
            bangDiem+="Điểm trung bình học kỳ: " + lblGPA.getText() + " - Xếp loại: " + lblXepLoai.getText();
            
            System.out.println(bangDiem);

            fw.write(bangDiem);
            fw.close();
            
        } catch (IOException ex) {
            Logger.getLogger(QLDiemPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnXuatBangDiemActionPerformed

    private void txtDiemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiemKeyTyped
        
        //lblDiemChu.setText(xepLoai(Float.parseFloat(txtDiem.getText()) ));      
                 
    }//GEN-LAST:event_txtDiemKeyTyped

    private void txtDiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiemKeyReleased
        if(!txtDiem.getText().equals(""))
            lblDiemChu.setText(xepLoai(Float.parseFloat(txtDiem.getText()) ));   
    }//GEN-LAST:event_txtDiemKeyReleased
  
    private void xacDinhMonHoc() {
        try {
            MonHocDao monHocDao = new MonHocDao();
            MonHoc monHoc = monHocDao.findByMaMon(txtMaMon.getText());
            lblTenMon.setText(monHoc.getTenMon());
            lblTinChi.setText(String.valueOf(monHoc.getSoTinChi()));
        } catch (SQLException ex) {
            MessageDialogHelper.showMessageDialog(parentFrame, "Không tìm thấy môn học", "Error");
            Logger.getLogger(QLDiemPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }    
    
    public String xepLoai(float diem){
        String kq = new String();
        kq = "A";
        if(diem < 9 && diem >= 8)
           kq = "B+";
        else if(diem < 8&& diem >= 7)
           kq = "B";
        else if(diem < 7&& diem >= 6.5)
           kq = "C+";
        else if(diem < 6.5&& diem >= 5.5)
           kq = "C";
        else if(diem < 5.5&& diem >= 5)
           kq = "D+";
        else if(diem < 5 && diem >= 4)
           kq = "D";
        else if(diem < 4)
           kq = "F";
        return kq;
    }
    
    private void roleSV(User user) throws SQLException, IOException{
        txtMaSinhVienSearch.setText( user.getUsername());
        txtMaSinhVienSearch.setEnabled(false);
        SinhVienDao svDao = new SinhVienDao();
        SinhVien sv = svDao.findByID(user.getUsername());
        txtHoTen.setText(sv.getHoTen());
        
        
        lblNhapDiem.setVisible(false);
        lblDiemChu1.setVisible(false);
        lblDiemSo.setVisible(false);
        lblSoTinChi1.setVisible(false);
        lblTenMon1.setVisible(false);
        lblMaMon.setVisible(false);
        txtDiem.setVisible(false);
        txtMaMon.setVisible(false);
        btnNew.setVisible(false);
        btnDelete.setVisible(false);
        btnSave.setVisible(false);
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnXuatBangDiem;
    private javax.swing.JComboBox<String> cbxHocKy;
    private javax.swing.JComboBox<String> cbxNamHoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblDiemChu;
    private javax.swing.JLabel lblDiemChu1;
    private javax.swing.JLabel lblDiemSo;
    private javax.swing.JLabel lblGPA;
    private javax.swing.JLabel lblMaMon;
    private javax.swing.JLabel lblNhapDiem;
    private javax.swing.JLabel lblSoTinChi1;
    private javax.swing.JLabel lblTenMon;
    private javax.swing.JLabel lblTenMon1;
    private javax.swing.JLabel lblTinChi;
    private javax.swing.JLabel lblXepLoai;
    private javax.swing.JTable tblGPA;
    private javax.swing.JTextField txtDiem;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaMon;
    private javax.swing.JTextField txtMaSinhVienSearch;
    // End of variables declaration//GEN-END:variables
}
